"""The pull request comment and check run for a PR run.

Each pull request gets exactly one Lantern comment. Its id is stored per (repo, PR); later
pushes update it. If the stored comment is gone (deleted by a user) or the id was never
stored (an earlier worker crashed between creating and recording it), the comment is found
by its hidden marker before a new one is created.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol

from lantern_platform.github import GitHub, GitHubError, RepoRef
from lantern_report.diff import FindingsDiff
from lantern_report.findings import Finding

MARKER = "<!-- lantern:dpia-pr-comment -->"
MAX_ROWS = 15
CHECK_NAME = "Lantern DPIA"
_RANK = {"critical": 4, "high": 3, "medium": 2, "low": 1, "informational": 0}


class CommentStore(Protocol):
    def get(self, repo: str, pr: int) -> int | None: ...

    def set(self, repo: str, pr: int, comment_id: int) -> None: ...


def _rows(findings: Sequence[Finding], report_url: str | None) -> list[str]:
    ordered = sorted(findings, key=lambda f: (-_RANK.get(f.severity, 0), f.id))
    out = []
    for f in ordered[:MAX_ROWS]:
        link = f"[{f.id}]({report_url}#{f.id.lower()})" if report_url else f.id
        cats = ", ".join(f.data_categories) or "-"
        out.append(f"| {link} | {f.severity} | {f.title} | {cats} | {f.status} |")
    if len(ordered) > MAX_ROWS:
        out.append(f"| | | {len(ordered) - MAX_ROWS} more in the full report | | |")
    return out


def render_pr_comment(
    diff: FindingsDiff,
    head_sha: str,
    base_sha: str | None,
    report_url: str | None,
    totals: dict[str, Any],
) -> str:
    lines = [
        MARKER,
        "### Lantern DPIA: findings diff",
        "",
        f"Head `{head_sha[:12]}`"
        + (f" against base `{base_sha[:12]}`" if base_sha else " (no base run)")
        + ": "
        f"**{len(diff.new)} new**, **{len(diff.resolved)} resolved**, "
        f"{len(diff.changed_severity)} changed severity, "
        f"{len(diff.changed_status)} changed status, "
        f"{diff.unchanged} unchanged. The head has {totals.get('findings', 0)} findings, "
        f"{totals.get('unresolved', 0)} unresolved.",
        "",
    ]
    header = ["| Finding | Severity | Title | Data | Status |", "|---|---|---|---|---|"]
    if diff.new:
        lines += ["#### New", "", *header, *_rows(diff.new, report_url), ""]
    if diff.resolved:
        lines += ["#### Resolved", "", *header, *_rows(diff.resolved, None), ""]
    changed = diff.changed_severity + diff.changed_status + diff.changed_classification
    if changed:
        lines += ["#### Changed", ""]
        seen: set[str] = set()
        for c in changed:
            if c.key in seen:
                continue
            seen.add(c.key)
            lines.append(
                f"- {c.after.id} {c.after.title}: "
                f"severity {c.before.severity} → {c.after.severity}, "
                f"status {c.before.status} → {c.after.status}"
            )
        lines.append("")
    if diff.is_empty:
        lines += ["No change in findings.", ""]
    if report_url:
        lines.append(f"[Full report]({report_url})")
    lines.append("")
    lines.append(
        "<sub>Generated by Lantern from the code at the head commit. Not legal advice.</sub>"
    )
    return "\n".join(lines)


def check_output(
    diff: FindingsDiff, totals: dict[str, Any], report_url: str | None
) -> dict[str, Any]:
    worst = max((_RANK.get(f.severity, 0) for f in diff.new), default=-1)
    title = (
        f"{len(diff.new)} new finding{'s' if len(diff.new) != 1 else ''}"
        if diff.new
        else "No new findings"
    )
    summary = (
        f"{len(diff.new)} new, {len(diff.resolved)} resolved, {diff.unchanged} unchanged. "
        f"{totals.get('findings', 0)} findings at the head, "
        f"{totals.get('unresolved', 0)} unresolved."
    )
    if report_url:
        summary += f" [Full report]({report_url})"
    # Lantern informs; it does not block merges. New high or critical findings are "neutral".
    return {
        "conclusion": "neutral" if worst >= _RANK["high"] else "success",
        "output": {"title": title, "summary": summary},
    }


def upsert_pr_comment(
    gh: GitHub, repo: RepoRef, pr: int, token: str, body: str, store: CommentStore
) -> tuple[int, str]:
    """Create or update the single Lantern comment on a pull request."""
    stored = store.get(repo.full_name, pr)
    if stored is not None:
        try:
            gh.update_issue_comment(repo, stored, token, body)
            return stored, "updated"
        except GitHubError as exc:
            if exc.status != 404:
                raise
    for comment in gh.list_issue_comments(repo, pr, token):
        if MARKER in str(comment.get("body", "")):
            comment_id = int(comment["id"])
            gh.update_issue_comment(repo, comment_id, token, body)
            store.set(repo.full_name, pr, comment_id)
            return comment_id, "updated"
    created = gh.create_issue_comment(repo, pr, token, body)
    store.set(repo.full_name, pr, int(created["id"]))
    return int(created["id"]), "created"
