"""JSON, Markdown, and self-contained HTML renderers for a ``Report``.

All three follow the same structure. Citations like ``[F-0042]`` become links to the
finding in the appendix; the finding lists its nodes and edges, each linked to the file and
line at the commit when the report knows the repository URL.
"""

from __future__ import annotations

import html
import json
import re
from typing import Any

from lantern_report.dpia import Report, Section, Table
from lantern_report.narrative import CITATION

DISCLAIMER = (
    "Generated by Lantern from the code at this commit. It describes what the code does; it "
    "is not legal advice, and sections marked for the controller need human answers."
)


def anchor(finding_id: str) -> str:
    return finding_id.lower()


# --------------------------------------------------------------------------- JSON


def render_json(report: Report) -> str:
    return json.dumps(report.to_dict(), indent=2, sort_keys=True, default=str)


# --------------------------------------------------------------------------- Markdown


def _md_cite(text: str) -> str:
    return CITATION.sub(lambda m: f"[[{m.group(1)}]](#{anchor(m.group(1))})", text)


def _md_cell(text: str) -> str:
    return _md_cite(str(text).replace("|", "\\|").replace("\n", " ")) or " "


def _md_link(text: str, url: str | None) -> str:
    return f"[{text}]({url})" if url else f"`{text}`"


def _md_table(table: Table) -> list[str]:
    if not table.rows:
        return [f"_{table.caption or 'Table'}: nothing to list._", ""]
    out = [f"**{table.caption}**", ""] if table.caption else []
    out.append("| " + " | ".join(table.columns) + " |")
    out.append("|" + "---|" * len(table.columns))
    out += ["| " + " | ".join(_md_cell(c) for c in row) + " |" for row in table.rows]
    return [*out, ""]


def _md_section(section: Section, level: int) -> list[str]:
    out = [f"{'#' * level} {section.title}", ""]
    if section.basis:
        out += [f"_Basis: {section.basis}_", ""]
    if section.intro:
        out += [section.intro, ""]
    if section.narrative and section.narrative.sentences:
        out += [_md_cite(" ".join(section.narrative.sentences)), ""]
    for table in section.tables:
        out += _md_table(table)
    for item in section.items:
        out += _md_unresolved(item, level + 1)
    for note in section.notes:
        out += [f"> {note}", ""]
    for child in section.children:
        out += _md_section(child, level + 1)
    return out


def _md_unresolved(item: dict[str, Any], level: int) -> list[str]:
    title = f"[{item['finding']}] {item['title']}" if item["finding"] else item["title"]
    out = [f"{'#' * level} {_md_cite(title)}", ""]
    flow = item["flow"]
    if flow.get("sources"):
        out.append(f"- **Sources:** {'; '.join(f'`{s}`' for s in flow['sources'])}")
    if flow.get("sink"):
        out.append(f"- **Sink:** {_md_link(flow['sink'], flow.get('sink_url'))}")
    if flow.get("destination"):
        out.append(f"- **Destination:** {flow['destination']}")
    for step in item["evidence"]:
        where = f"{step.get('file')}:{step.get('line')}"
        out.append(
            f"- **Unresolved step:** {_md_link(where, step.get('url'))} `{step.get('text', '')}`"
            f" ({step.get('note', '')})"
        )
    for d in item["decisions"]:
        out.append(
            f"- **Low-confidence decision:** {d['question']} = `{d['answer']}` "
            f"(p = {d['probability']:.2f})"
        )
    out += ["", "**Reviewer must check:**", ""]
    out += [f"{n}. {text}" for n, text in enumerate(item["instructions"], 1)]
    return [*out, ""]


def _md_finding(f: dict[str, Any]) -> list[str]:
    out = [
        f'### <a id="{anchor(f["id"])}"></a>{f["id"]}: {f["title"]}',
        "",
        f"- **Severity:** {f['severity']} ({', '.join(f['severity_modifiers']) or 'base'}); "
        f"**status:** {f['status']}; **likelihood:** {f['likelihood']}",
        f"- **Data:** {', '.join(f['data_categories']) or '-'}; "
        f"**destination class:** {f['destination_class'] or '-'}",
        f"- **Anchor:** {_md_link(f['anchor_id'], f.get('anchor_url'))}",
    ]
    if f.get("verification"):
        v = f["verification"]
        out.append(f"- **Dynamic verification:** {v.get('status')} ({v.get('reason')})")
    out.append(f"- **Statutes:** {', '.join(f['statute_refs']) or '-'}")
    out.append(f"- **Measure:** {f['measure']}")
    out += ["", "Nodes:", ""]
    for n in f["nodes"]:
        loc = f"{n['file']}:{n['line_start']}"
        out.append(f"- `{n['id']}` {n['kind']} `{n['symbol']}` at {_md_link(loc, n['url'])}")
    if f["edges"]:
        out += ["", "Edges:", ""]
        for e in f["edges"]:
            out.append(f"- `{e['id']}` {e['from']} → {e['to']}")
            for s in e["steps"]:
                loc = f"{s['file']}:{s['line']}"
                flag = " **unresolved**" if s.get("unresolved") else ""
                out.append(f"  - {_md_link(loc, s.get('url'))} {s['kind']}{flag}")
    if f["decisions"]:
        out += ["", "Decisions:", ""]
        for d in f["decisions"]:
            out.append(
                f"- `{d['id']}` {d['target_id']} {d['question']} = `{d['answer']}` "
                f"(p = {d['probability']:.2f}, {d['provider']})"
            )
    return [*out, ""]


def render_markdown(report: Report) -> str:
    run = report.run
    s = report.summary
    out = [
        f"# Data protection impact assessment: {run.repo}",
        "",
        f"Commit `{run.commit}` · run `{run.run_id or '-'}` · generated {run.generated_at} · "
        f"decision provider `{s['provider'] or '-'}` ({s['provider_version'] or '-'}) · question "
        f"set {s['question_set_version'] or '-'} · threshold {s['threshold']} · narrative: "
        f"{', '.join(s.get('narrative', [])) or 'template'}",
        "",
        f"> {DISCLAIMER}",
        "",
        f"**{s['findings']} findings**: "
        + ", ".join(f"{v} {k}" for k, v in sorted(s["by_severity"].items()))
        + f"; {s['unresolved']} unresolved.",
        "",
    ]
    for section in report.sections:
        out += _md_section(section, 2)
    out += ["## Appendix A. Findings", ""]
    for f in report.findings:
        out += _md_finding(f)
    out += ["## Appendix B. Statute references", ""]
    for ref in report.statutes.values():
        verify = " (re-check before relying on it)" if ref.get("verify") else ""
        note = f" {ref['note']}" if ref.get("note") else ""
        out.append(f"- **{ref['id']}**: {ref['citation']}, {ref['title']}.{note}{verify}")
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- HTML

CSS = """
:root{--bg:#fbfbf9;--fg:#1d1f21;--muted:#5b6166;--line:#d9dcd6;--panel:#ffffff;
--accent:#1f5f8b;--crit:#9b1c1c;--high:#b4491b;--med:#8a6d00;--low:#3f6b3f;--info:#56606a}
@media (prefers-color-scheme:dark){:root{--bg:#141618;--fg:#e6e6e3;--muted:#a3a9ae;
--line:#30353a;--panel:#1c1f22;--accent:#7cb7e6;--crit:#f08c8c;--high:#f0a878;--med:#e6cc6a;
--low:#9cd29c;--info:#aab3bb}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:1080px;margin:0 auto;padding:24px 16px 64px}
h1{font-size:1.7rem;margin:0 0 4px}h2{margin-top:2.2em;border-bottom:1px solid var(--line);
padding-bottom:4px}h3{margin-top:1.6em}h4{margin:1.2em 0 .4em}
a{color:var(--accent)}code{font:13px ui-monospace,SFMono-Regular,Menlo,monospace}
.meta,.basis{color:var(--muted);font-size:.9rem}.disclaimer{border-left:3px solid var(--line);
padding:6px 12px;color:var(--muted)}.note{border-left:3px solid var(--accent);padding:6px 12px;
background:var(--panel)}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;
margin:8px 0 16px;font-size:.9rem;background:var(--panel)}th,td{border:1px solid var(--line);
padding:6px 8px;text-align:left;vertical-align:top}th{font-weight:600}
details{border:1px solid var(--line);border-radius:6px;background:var(--panel);margin:8px 0;
padding:0 12px}summary{cursor:pointer;padding:10px 0;font-weight:600}
details[open]>summary{border-bottom:1px solid var(--line);margin-bottom:8px}
.sev{display:inline-block;min-width:92px;font-size:.8rem;font-weight:600;text-transform:uppercase}
.sev-critical{color:var(--crit)}.sev-high{color:var(--high)}.sev-medium{color:var(--med)}
.sev-low{color:var(--low)}.sev-informational{color:var(--info)}
pre{background:var(--bg);border:1px solid var(--line);padding:8px;overflow-x:auto;
white-space:pre-wrap}ol.instr li{margin:4px 0}
"""
JS = """
function openTarget(){var id=location.hash.slice(1);if(!id)return;
var el=document.getElementById(id);if(el&&el.tagName==='DETAILS'){el.open=true;}}
window.addEventListener('hashchange',openTarget);document.addEventListener('DOMContentLoaded',openTarget);
"""


def _h(text: Any) -> str:
    return html.escape(str(text), quote=True)


def _html_cite(text: str) -> str:
    escaped = _h(text)
    return CITATION.sub(
        lambda m: f'<a class="cite" href="#{anchor(m.group(1))}">[{m.group(1)}]</a>', escaped
    )


def _html_link(text: str, url: str | None) -> str:
    return f'<a href="{_h(url)}">{_h(text)}</a>' if url else f"<code>{_h(text)}</code>"


def _html_table(table: Table) -> str:
    if not table.rows:
        return f'<p class="meta">{_h(table.caption or "Table")}: nothing to list.</p>'
    head = "".join(f"<th>{_h(c)}</th>" for c in table.columns)
    body = "".join(
        "<tr>" + "".join(f"<td>{_html_cite(str(c))}</td>" for c in row) + "</tr>"
        for row in table.rows
    )
    caption = f"<caption>{_h(table.caption)}</caption>" if table.caption else ""
    return (
        f'<div class="scroll"><table>{caption}<thead><tr>{head}</tr></thead>'
        f"<tbody>{body}</tbody></table></div>"
    )


def _html_unresolved(item: dict[str, Any]) -> str:
    title = f"[{item['finding']}] {item['title']}" if item["finding"] else item["title"]
    flow = item["flow"]
    parts = [f"<h4>{_html_cite(title)}</h4><ul>"]
    if flow.get("sources"):
        parts.append(
            "<li><b>Sources:</b> "
            + "; ".join(f"<code>{_h(s)}</code>" for s in flow["sources"])
            + "</li>"
        )
    if flow.get("sink"):
        parts.append(f"<li><b>Sink:</b> {_html_link(flow['sink'], flow.get('sink_url'))}</li>")
    if flow.get("destination"):
        parts.append(f"<li><b>Destination:</b> {_h(flow['destination'])}</li>")
    for step in item["evidence"]:
        where = f"{step.get('file')}:{step.get('line')}"
        parts.append(
            f"<li><b>Unresolved step:</b> {_html_link(where, step.get('url'))} "
            f"<code>{_h(step.get('text', ''))}</code> ({_h(step.get('note', ''))})</li>"
        )
    for d in item["decisions"]:
        parts.append(
            f"<li><b>Low-confidence decision:</b> {_h(d['question'])} = "
            f"<code>{_h(d['answer'])}</code> "
            f"(p = {d['probability']:.2f})</li>"
        )
    parts.append('</ul><p><b>Reviewer must check:</b></p><ol class="instr">')
    parts += [f"<li>{_html_cite(i)}</li>" for i in item["instructions"]]
    parts.append("</ol>")
    return "".join(parts)


def _html_section(section: Section, level: int) -> str:
    tag = f"h{min(level, 6)}"
    parts = [f'<section id="sec-{_h(section.id)}"><{tag}>{_h(section.title)}</{tag}>']
    if section.basis:
        parts.append(f'<p class="basis">Basis: {_h(section.basis)}</p>')
    if section.intro:
        parts.append(f"<p>{_h(section.intro)}</p>")
    if section.narrative and section.narrative.sentences:
        parts.append(
            f'<p class="narrative">{_html_cite(" ".join(section.narrative.sentences))}</p>'
        )
    parts += [_html_table(t) for t in section.tables]
    parts += [_html_unresolved(i) for i in section.items]
    parts += [f'<p class="note">{_h(n)}</p>' for n in section.notes]
    parts += [_html_section(c, level + 1) for c in section.children]
    parts.append("</section>")
    return "".join(parts)


def _html_finding(f: dict[str, Any]) -> str:
    rows = [
        ("Severity", f"{f['severity']} ({', '.join(f['severity_modifiers']) or 'base'})"),
        ("Status", f["status"]),
        ("Likelihood", f["likelihood"]),
        ("Data categories", ", ".join(f["data_categories"]) or "-"),
        ("Destination class", f["destination_class"] or "-"),
        ("Dynamic verification", (f.get("verification") or {}).get("status", "not run")),
        ("Statutes", ", ".join(f["statute_refs"]) or "-"),
        ("Measure", f["measure"]),
    ]
    meta = "".join(f"<tr><th>{_h(k)}</th><td>{_h(v)}</td></tr>" for k, v in rows)
    nodes = "".join(
        f"<li><code>{_h(n['id'])}</code> {_h(n['kind'])} <code>{_h(n['symbol'])}</code> at "
        f"{_html_link(f'{n["file"]}:{n["line_start"]}', n['url'])}"
        + (f"<pre>{_h(n['snippet'])}</pre>" if n.get("snippet") else "")
        + "</li>"
        for n in f["nodes"]
    )
    edges = ""
    for e in f["edges"]:
        items = []
        for st in e["steps"]:
            flag = f" <b>unresolved</b>: {_h(st.get('note', ''))}" if st.get("unresolved") else ""
            where = _html_link(f"{st['file']}:{st['line']}", st.get("url"))
            items.append(f"<li>{where} {_h(st['kind'])} <code>{_h(st['text'])}</code>{flag}</li>")
        steps = "".join(items)
        edges += (
            f"<li><code>{_h(e['id'])}</code> {_h(e['from'])} → {_h(e['to'])}<ol>{steps}</ol></li>"
        )
    decisions = "".join(
        f"<tr><td><code>{_h(d['id'])}</code></td><td>{_h(d['target_id'])}</td><td>{_h(d['question'])}</td>"
        f"<td>{_h(d['answer'])}</td><td>{d['probability']:.2f}</td><td>{_h(d['provider'])}</td></tr>"
        for d in f["decisions"]
    )
    decision_table = (
        "<table><thead><tr><th>Decision</th><th>Target</th><th>Question</th><th>Answer</th>"
        f"<th>p</th><th>Provider</th></tr></thead><tbody>{decisions}</tbody></table>"
        if decisions
        else ""
    )
    return (
        f'<details id="{anchor(f["id"])}"><summary><span class="sev sev-{_h(f["severity"])}">'
        f"{_h(f['severity'])}</span> {_h(f['id'])}: {_h(f['title'])}</summary>"
        f'<div class="scroll"><table>{meta}</table></div>'
        f"<h4>Nodes</h4><ul>{nodes}</ul>"
        + (f"<h4>Edges</h4><ul>{edges}</ul>" if edges else "")
        + (
            f'<h4>Decisions</h4><div class="scroll">{decision_table}</div>'
            if decision_table
            else ""
        )
        + "</details>"
    )


def render_html(report: Report) -> str:
    run = report.run
    s = report.summary
    counts = ", ".join(f"{v} {k}" for k, v in sorted(s["by_severity"].items()))
    body = [
        f"<h1>Data protection impact assessment: {_h(run.repo)}</h1>",
        f'<p class="meta">Commit <code>{_h(run.commit)}</code> · run '
        f"<code>{_h(run.run_id or '-')}</code> "
        f"· generated {_h(run.generated_at)} · decision provider "
        f"<code>{_h(s['provider'] or '-')}</code> "
        f"· question set {_h(s['question_set_version'] or '-')} · threshold {_h(s['threshold'])} "
        f"· narrative: {_h(', '.join(s.get('narrative', [])) or 'template')}</p>",
        f'<p class="disclaimer">{_h(DISCLAIMER)}</p>',
        f"<p><b>{s['findings']} findings</b>: {_h(counts)}; {s['unresolved']} unresolved.</p>",
    ]
    body += [_html_section(sec, 2) for sec in report.sections]
    body.append('<section id="sec-appendix-findings"><h2>Appendix A. Findings</h2>')
    body += [_html_finding(f) for f in report.findings]
    body.append(
        '</section><section id="sec-appendix-statutes"><h2>Appendix B. Statute references</h2><ul>'
    )
    for ref in report.statutes.values():
        verify = " (re-check before relying on it)" if ref.get("verify") else ""
        note = f" {ref['note']}" if ref.get("note") else ""
        body.append(
            f"<li><b>{_h(ref['id'])}</b>: {_h(ref['citation'])}, "
            f"{_h(ref['title'])}.{_h(note)}{_h(verify)}</li>"
        )
    body.append("</ul></section>")
    title = f"DPIA {run.repo}"
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"<title>{_h(title)}</title><style>{CSS}</style><script>{JS}</script></head>"
        f"<body><main>{''.join(body)}</main></body></html>\n"
    )


def citations_in(text: str) -> set[str]:
    return set(CITATION.findall(text))


def finding_anchor_ids(markup: str) -> set[str]:
    return {m.upper() for m in re.findall(r'id="(f-\d{4,})"', markup)}
